### ISSUE TITLE
error: 'WiFiClientSecure' was not declared in this scope; did you mean 'WiFiClient'?

### ISSUE THREAD

**Issue by adrianwFPS** [pxsty0/DisCard#1]
error: 'WiFiClientSecure' was not declared in this scope; did you mean 'WiFiClient'?

error: 'client' was not declared in this scope; did you mean 'Client'?

and so on.

Any ideas? Is this a conflict of wifi.h being called twice or something?

**Comment by pxsty0** [comment]
Hello, thank you for reporting this error, the error is caused by the library, I will publish a new version of the library after solving the problem.

**Comment by pxsty0** [comment]
The bug has been fixed, I will be glad if you follow my profile and star the project, good use!

**Comment by adrianwFPS** [comment]
awesome, many thanks.
